AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Carousel Lambda Function.

Resources:
  Carousel:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: ./
      Handler: handler.carousel
      Runtime: nodejs18.x
      Events:
        ApiEvent:
          Type: HttpApi
      Environment:
        Variables:
          PORT: 8000
          MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
          MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}

Outputs:
  CarouselApi:
    Description: URL of your API endpoint
    Value: 'https://${HttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/${StageName}/'
