AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Carousel Lambda Function.

Parameters:
  MONGODB_PASSWORD:
    Type: String
    Description: Password for MongoDB

Resources:
  Carousel:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: ./
      Handler: handler.carousel
      Runtime: nodejs18.x
      Events:
        ApiEvent:
          Type: HttpApi
      Environment:
        Variables:
          PORT: 8000
          MONGODB_USERNAME: yasitharanga1
          MONGODB_PASSWORD: !Ref MONGODB_PASSWORD

Outputs:
  CarouselApi:
    Description: URL of your API endpoint
    Value: 'https://${HttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/${StageName}/'
